# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, choices=[('housing', 'Housing'), ('parks', 'Parks'), ('schools', 'Schools'), ('safety', 'Public Safety')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='no_votes',
            field=models.ManyToManyField(blank=True, related_name='no', to='votes.Voter'),
        ),
        migrations.AddField(
            model_name='vote',
            name='yes_votes',
            field=models.ManyToManyField(blank=True, related_name='yes', to='votes.Voter'),
        ),
    ]
